spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/decidish
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
  session:
     store-type: jdbc
     jdbc:
       initialize-schema: always
#    store-type: none
  application:
    name: "shopping-service"

cron:
  weekly-sync: "0 0 3 ? * SUN"  # Every Sunday at 3 AM
  quick-sync: "*/30 * * * * *"  # Every 30 seconds (for testing)