services:
  # ----------------------------------------------------------------
  # Databases & Cache
  # ----------------------------------------------------------------

  # PostgreSQL with pgvector
  db_backend:
    image: pgvector/pgvector:pg16
    container_name: dev_backend_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_backend_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  db_authorisation:
    image: postgres:16-alpine
    container_name: dev_auth_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_authorisation_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: dev_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # ----------------------------------------------------------------
  # Application Services
  # ----------------------------------------------------------------

  # Authorization Server
  authorization-server:
    build: ./backend/authorization
    container_name: dev_authorization
    ports:
      - "8083:8083"
    volumes:
      - ./backend/authorization:/app
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db_authorisation
    networks:
      - app-network

  # Core Server
  core-server:
    build: ./backend/core
    container_name: dev_core
    ports:
      - "8080:8080"
    volumes:
      - ./backend/core:/app
      - ~/.gradle:/home/gradle/.gradle
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_backend:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      - db_backend
      - redis
    networks:
      - app-network

  # Personalization Server
  personalization-server:
    build: ./backend/personalization
    container_name: dev_personalization
    ports:
      - "8082:8082"
    volumes:
      - ./backend/personalization:/app
    environment:
      - DB_HOST=db_backend
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_BACKEND_URL}
      - EMBEDDER_SERVER_URL=${EMBEDDER_SERVER_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_RECIPES_BUCKET=${MINIO_RECIPES_BUCKET}
      - MINIO_RECIPES_OBJECT=${MINIO_RECIPES_OBJECT}
    depends_on:
      - db_backend
    networks:
      - app-network

  # MLPipeline
  mlpipeline:
    build: ./mlpipeline
    container_name: dev_mlpipeline
    ports:
      - "8000:8000"
    volumes:
      - ./mlpipeline:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_backend:5432/${POSTGRES_DB}
    depends_on:
      - db_backend
    networks:
      - app-network

  client-web:
    image: decidish/client-web:${IMAGE_TAG}
    ports:
      - "3000:3000"
    deploy:
      update_config:
        order: start-first
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3000" ]
      interval: 10s
      retries: 3
      start_period: 5s

  # ----------------------------------------------------------------
  # Monitoring
  # ----------------------------------------------------------------

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - app-network


# ----------------------------------------------------------------
# Volumes & Networks
# ----------------------------------------------------------------
volumes:
  db_backend_data:
  db_authorisation_data:
  prometheus_data:

networks:
  app-network:
    driver: bridge