services:
  # ----------------------------------------------------------------
  # Databases & Cache
  # ----------------------------------------------------------------

  # Migrations
#  export GOOSE_DBSTRING="postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=${DB_SSLMODE:-disable}&search_path=${DB_SCHEMA:-public}"

  migrator:
    build:
      context: ./migrations
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db_backend
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db_backend:
        condition: service_healthy
    networks:
        - app-network

  # PostgreSQL with pgvector
  db_backend:
    image: pgvector/pgvector:pg16
    container_name: dev_backend_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_backend_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db_authorisation:
    image: postgres:16-alpine
    container_name: dev_auth_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_authorisation_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: dev_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # ----------------------------------------------------------------
  # Application Services
  # ----------------------------------------------------------------

  # Authorization Server
  authorization-server:
    build: ./backend/authorization
    container_name: dev_authorization
    ports:
      - "8083:8083"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db_authorisation:
        condition: service_healthy
    networks:
      - app-network

  # Core Server
  core-server:
    build: ./backend/core
    container_name: dev_core
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_backend:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
    networks:
      - app-network

  # Personalization Server
  personalization-server:
    build: ./backend/personalization
    container_name: dev_personalization
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db_backend
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_BACKEND_URL}
      - EMBEDDER_SERVER_URL=http://mlpipeline:8000
    depends_on:
      migrator:
        condition: service_completed_successfully
    networks:
      - app-network

  # MLPipeline
  mlpipeline:
    build: ./mlpipeline
    container_name: dev_mlpipeline
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db_backend
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
      - DATABASE_BACKEND_CONNECTION_STRING=${DATABASE_BACKEND_CONNECTION_STRING}
      - ADAPTER_CKPT_DIR=/app/models/adapter_checkpoints
    volumes:
      - ./ckpts_weekly_user_adapter:/app/models/adapter_checkpoints
    depends_on:
      - personalization-server
    networks:
      - app-network

  client-web:
    build: 
      context: ./client
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    container_name: dev_client
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    deploy:
      update_config:
        order: start-first
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3000" ]
      interval: 10s
      retries: 3
      start_period: 5s

  # ----------------------------------------------------------------
  # Reverse Proxy
  # ----------------------------------------------------------------
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - authorization-server
      - core-server
      - personalization-server
    networks:
      - app-network

  # ----------------------------------------------------------------
  # Monitoring
  # ----------------------------------------------------------------

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3031:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - app-network
  
  cronicle:
    image: soulteary/cronicle:latest
    container_name: cronicle
    ports:
      - "3012:3012"
    environment:
      - TZ=UTC
    volumes:
      - ./chronicle/data:/opt/cronicle/data
      - ./chronicle/logs:/opt/cronicle/logs
    networks:
      - app-network


# ----------------------------------------------------------------
# Volumes & Networks
# ----------------------------------------------------------------
volumes:
  db_backend_data:
  db_authorisation_data:
  prometheus_data:

networks:
  app-network:
    driver: bridge