preferences = [
    "low_sugar",
    "low_carb",
    "high_carb",
    "high_protein",
    "low_fat",
    "cholesterol_low",
    "high_fiber",
    "healthy_fats",
    "gluten_free",
    "lactose_free",
    "vegan",
    "vegetarian",
    "paleo",
    "keto",
    "histamine_low",
    "pregnancy_safe",
    "light_diet",
    "weight_loss",
    "muscle_gain",
    "endurance_training",
    "marathon_training",
    "quick_after_work",
    "office_lunch",
    "camping",
    "party_food",
    "picnic",
    "seasonal_preferences",
    "air_fryer",
    "grill",
    "frying",
    "steaming",
    "fermenting",
    "oven_cooking",
    "pressure_cooker",
    "thermomix_user"
]


keyword_preference_map = {
    # Health Preferences
    "Zuckerfrei": "low_sugar",
    "Low Carb": "low_carb",
    "High Carb": "high_carb",
    "High Protein": "high_protein",
    "Fettarm": "low_fat",
    "Cholesterinarm": "cholesterol_low",
    "Ballaststoffreich": "high_fiber",
    "Gesunde Fette": "healthy_fats",
    "Kalorienarm": "weight_loss",
    "Fettabbau": "weight_loss",
    "Muskelaufbau": "muscle_gain",
    "Diät": "weight_loss",
    "Clean Eating": "light_diet",
    "gesund": "light_diet",

    # Philosophy
    "Vegan": "vegan",
    "Vegetarisch": "vegetarian",
    "Paleo": "paleo",
    "Ketogene Diät": "keto",
    "Histaminarme Rezepte": "histamine_low",
    "Schwangerschaft": "pregnancy_safe",
    "Schonkost": "light_diet",
    "Laktosefrei": "lactose_free",
    "Glutenfrei": "gluten_free",
    "Darmsanierung": "light_diet",
    "Scheinfasten-Rezepte": "light_diet",

    # Sports
    "Fitness": "muscle_gain",
    "Ausdauersport": "endurance_training",
    "Marathon-Rezepte": "marathon_training",
    "Sport": "endurance_training",

    # Lifestyle Preferences
    "Feierabend": "quick_after_work",
    "Büro": "office_lunch",
    "Camping": "camping",
    "Party": "party_food",
    "Picknick": "picnic",
    "Sommer": "seasonal_preferences",
    "Winter": "seasonal_preferences",
    "Frühling": "seasonal_preferences",
    "Herbst": "seasonal_preferences",
    "Katerfrühstück": "light_diet",
    "Adventsbrunch": "seasonal_preferences",

    # Cooking Style Preferences
    "Heißluftfritteuse": "air_fryer",
    "Kontaktgrill-Rezepte": "grill",
    "Grillen": "grill",
    "frittieren": "frying",
    "Fermentieren": "fermenting",
    "Einlegen": "fermenting",
    "Einmachen": "fermenting",
    "Ofengericht": "oven_cooking",
    "Ofengemüse": "oven_cooking",
    "Frittata": "frying",
    "Dampfgarer-Rezepte": "steaming",
    "Römertopf": "oven_cooking",
    "Schnellkochtopf": "pressure_cooker",
    "Thermomix": "thermomix_user",
}
