--CREATE SEQUENCE IF NOT EXISTS market_sequence START WITH 1 INCREMENT BY 1;
--CREATE SEQUENCE IF NOT EXISTS address_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE markets
(
--    id              BIGINT  NOT NULL DEFAULT nextval('market_sequence'),
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rewe_id         VARCHAR(50) NOT NULL UNIQUE,
    name            VARCHAR(255),
    address_id      BIGINT,
    -- is_open    BOOLEAN NOT NULL,
    last_updated    TIMESTAMP,
    CONSTRAINT pk_markets PRIMARY KEY (id)
);

ALTER TABLE markets
    ADD CONSTRAINT uc_markets_address UNIQUE (address_id);

CREATE TABLE addresses
(
    --id              BIGINT NOT NULL DEFAULT nextval('address_seq'),
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street          VARCHAR(255),
    zip_code        VARCHAR(255),
    city            VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

ALTER TABLE markets
    ADD CONSTRAINT fk_markets_on_address FOREIGN KEY (address_id) REFERENCES addresses(id);
    
CREATE INDEX idx_address_zipcode ON addresses(zip_code);
CREATE INDEX idx_market_rewe_id ON markets(rewe_id);
