name: Authorization-Service-CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/authorization/**'
      - '.github/workflows/authorization-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/authorization/**'
      - '.github/workflows/authorization-ci.yml'

jobs:
  build:
    uses: ./.github/workflows/templates/go-ci.yml
    with:
      service_dir: 'backend/authorization'
      image_name: 'decidish/auth-service'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}